# Generated by Django 2.2.10 on 2021-07-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='poll_name',
            new_name='poll_title',
        ),
    ]
