# Generated by Django 2.2.10 on 2021-07-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_auto_20210714_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='poll_description',
            new_name='description',
        ),
    ]
